config/routes.rb
RocketProvisioner::Application.routes.draw do

  get "report_instances/show"

  get "report_instances/index"

  resources :report_results

  resources :reports do 
    resources :report_instances
    member do 
      get 'run'
    end
  end


  resources :rocket_files

  resources :folders

  resources :payload_groups do 
    member do 
      get 'run/:object_type/:object_id', :to => "payload_groups#run", :as => "run"
      post 'add_payload'
      get 'payload/:payload_id/run', :as => 'run_payload', :to => "server_groups#run"
    end
  end


  resources :payloads

  resources :server_roles

  resources :payload_histories

  resources :servers do 
    resources :payload_histories
    member do 
      get 'payload/:payload_id/run', :as => 'run_payload', :to => "servers#run"
    end
  end

  root :to => "server_groups#index"

  resources :server_groups

  require 'resque'

  mount Resque::Server.new, :at => "/resque"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name
end

app/models/installed_payload.rb
class InstalledPayload < ActiveRecord::Base
  attr_accessible :payload_id, :server_id
end

app/models/payload.rb
class Payload < ActiveRecord::Base
  attr_accessible :name, :script, :payload_type
  belongs_to :payload_group_payloads
  scope :scripts, where(:payload_type => 'script')
  scope :packages, where(:payload_type => 'package')
  def to_s 
    name
  end
end

app/models/payload_group.rb
class PayloadGroup < ActiveRecord::Base
  attr_accessible :name
  has_many :payload_group_payloads
  has_many :payloads, :through => :payload_group_payloads
  validates_presence_of :name
end

app/models/payload_history.rb
class PayloadHistory < ActiveRecord::Base
  attr_accessible :output, :payload_id, :return_code, :server_id, :finished
  belongs_to :payload 
  belongs_to :server

  default_scope order('id desc')
  scope :pending, where(:finished => false)
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :name, :payload_id
  has_many :report_instances
  belongs_to :payload
end

app/models/report_instance.rb
class ReportInstance < ActiveRecord::Base
  attr_accessible :report_id
  belongs_to :report 
  has_many :report_results
end

app/models/report_result.rb
class ReportResult < ActiveRecord::Base
  attr_accessible :report_id, :result, :server_id, :report_instance_id
  belongs_to :report 
  belongs_to :report_instance
  belongs_to :server
end

app/models/rocket_file.rb
class RocketFile < ActiveRecord::Base
  attr_accessible :content, :folder_id, :name
end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :dns_name, :ip_address, :server_group_id, :server_role_id, :ssh_user
  validates_presence_of :server_group_id, :dns_name, :ip_address
  belongs_to :server_group
  belongs_to :server_role

  has_many :payload_history

  def payload_installed?(payload)
    InstalledPayload.where(:server_id => self.id, :payload_id => payload.id).count > 0 ? true : false
  end

  def to_s 
    "#{dns_name} (#{ip_address})"
  end

end

app/models/server_group.rb
class ServerGroup < ActiveRecord::Base
  attr_accessible :name
  has_many :servers

  def to_s 
    name
  end
end

app/models/server_role.rb
class ServerRole < ActiveRecord::Base
  attr_accessible :name
  has_many :servers
end

app/controllers/server_roles_controller.rb
class ServerRolesController < ApplicationController
  # GET /server_roles
  # GET /server_roles.json
  def index
    @server_roles = ServerRole.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @server_roles }
    end
  end

  # GET /server_roles/1
  # GET /server_roles/1.json
  def show
    @server_role = ServerRole.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @server_role }
    end
  end

  # GET /server_roles/new
  # GET /server_roles/new.json
  def new
    @server_role = ServerRole.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @server_role }
    end
  end

  # GET /server_roles/1/edit
  def edit
    @server_role = ServerRole.find(params[:id])
  end

  # POST /server_roles
  # POST /server_roles.json
  def create
    @server_role = ServerRole.new(params[:server_role])

    respond_to do |format|
      if @server_role.save
        format.html { redirect_to @server_role, notice: 'Server role was successfully created.' }
        format.json { render json: @server_role, status: :created, location: @server_role }
      else
        format.html { render action: "new" }
        format.json { render json: @server_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /server_roles/1
  # PUT /server_roles/1.json
  def update
    @server_role = ServerRole.find(params[:id])

    respond_to do |format|
      if @server_role.update_attributes(params[:server_role])
        format.html { redirect_to @server_role, notice: 'Server role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @server_role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /server_roles/1
  # DELETE /server_roles/1.json
  def destroy
    @server_role = ServerRole.find(params[:id])
    @server_role.destroy

    respond_to do |format|
      format.html { redirect_to server_roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/gyro_parts_helper.rb
module GyroPartsHelper
end

app/helpers/gyros_helper.rb
module GyrosHelper
end

app/helpers/payloads_helper.rb
module PayloadsHelper
  def payload_linkable(txt, obj,  payload, action = nil, css) 
    if obj.is_a?(Server)
      link_to txt, run_payload_server_path(obj.id, payload.id, :package_action => action), :class => css, :remote => true
    elsif obj.is_a?(ServerGroup)
      link_to txt, run_payload_payload_group_path(obj.id, payload.id, :package_action => action), :class => css, :remote => true
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rocket_files_helper.rb
module RocketFilesHelper
end

app/helpers/server_roles_helper.rb
module ServerRolesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/server_roles/_form.html.haml
= form_for @server_role, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), server_roles_path, :class => 'btn'

app/views/server_roles/edit.html.haml
- model_class = @server_role.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/server_roles/index.html.haml
- model_class = ServerRole.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @server_roles.each do |server_role|
      %tr
        %td= link_to server_role.id, server_role_path(server_role)
        %td= server_role.name
        %td=l server_role.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_server_role_path(server_role), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), server_role_path(server_role), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_server_role_path, :class => 'btn btn-primary'

app/views/server_roles/new.html.haml
- model_class = @server_role.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/server_roles/show.html.haml
- model_class = @server_role.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @server_role.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), server_roles_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_server_role_path(@server_role), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), server_role_path(@server_role), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'