config/routes.rb
RocketProvisioner::Application.routes.draw do

  get "report_instances/show"

  get "report_instances/index"

  resources :report_results

  resources :reports do 
    resources :report_instances
    member do 
      get 'run'
    end
  end


  resources :rocket_files

  resources :folders

  resources :payload_groups do 
    member do 
      get 'run/:object_type/:object_id', :to => "payload_groups#run", :as => "run"
      post 'add_payload'
      get 'payload/:payload_id/run', :as => 'run_payload', :to => "server_groups#run"
    end
  end


  resources :payloads

  resources :server_roles

  resources :payload_histories

  resources :servers do 
    resources :payload_histories
    member do 
      get 'payload/:payload_id/run', :as => 'run_payload', :to => "servers#run"
    end
  end

  root :to => "server_groups#index"

  resources :server_groups

  require 'resque'

  mount Resque::Server.new, :at => "/resque"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name
end

app/models/installed_payload.rb
class InstalledPayload < ActiveRecord::Base
  attr_accessible :payload_id, :server_id
end

app/models/payload.rb
class Payload < ActiveRecord::Base
  attr_accessible :name, :script, :payload_type
  belongs_to :payload_group_payloads
  scope :scripts, where(:payload_type => 'script')
  scope :packages, where(:payload_type => 'package')
  def to_s 
    name
  end
end

app/models/payload_group.rb
class PayloadGroup < ActiveRecord::Base
  attr_accessible :name
  has_many :payload_group_payloads
  has_many :payloads, :through => :payload_group_payloads
  validates_presence_of :name
end

app/models/payload_history.rb
class PayloadHistory < ActiveRecord::Base
  attr_accessible :output, :payload_id, :return_code, :server_id, :finished
  belongs_to :payload 
  belongs_to :server

  default_scope order('id desc')
  scope :pending, where(:finished => false)
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :name, :payload_id
  has_many :report_instances
  belongs_to :payload
end

app/models/report_instance.rb
class ReportInstance < ActiveRecord::Base
  attr_accessible :report_id
  belongs_to :report 
  has_many :report_results
end

app/models/report_result.rb
class ReportResult < ActiveRecord::Base
  attr_accessible :report_id, :result, :server_id, :report_instance_id
  belongs_to :report 
  belongs_to :report_instance
  belongs_to :server
end

app/models/rocket_file.rb
class RocketFile < ActiveRecord::Base
  attr_accessible :content, :folder_id, :name
end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :dns_name, :ip_address, :server_group_id, :server_role_id, :ssh_user
  validates_presence_of :server_group_id, :dns_name, :ip_address
  belongs_to :server_group
  belongs_to :server_role

  has_many :payload_history

  def payload_installed?(payload)
    InstalledPayload.where(:server_id => self.id, :payload_id => payload.id).count > 0 ? true : false
  end

  def to_s 
    "#{dns_name} (#{ip_address})"
  end

end

app/models/server_group.rb
class ServerGroup < ActiveRecord::Base
  attr_accessible :name
  has_many :servers

  def to_s 
    name
  end
end

app/models/server_role.rb
class ServerRole < ActiveRecord::Base
  attr_accessible :name
  has_many :servers
end

app/controllers/payload_groups_controller.rb
class PayloadGroupsController < ApplicationController

  def add_payload
    PayloadGroupPayload.create(:payload_id => params[:pg][:payload_id], :payload_group_id => params[:id])
    redirect_to payload_group_path(params[:id]), notice: "Payload added to group."
  end

  def index
    @payload_groups = PayloadGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payload_groups }
    end
  end

  def show
    @payload_group = PayloadGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payload_group }
    end
  end

  # GET /payload_groups/new
  # GET /payload_groups/new.json
  def new
    @payload_group = PayloadGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payload_group }
    end
  end

  # GET /payload_groups/1/edit
  def edit
    @payload_group = PayloadGroup.find(params[:id])
  end

  # POST /payload_groups
  # POST /payload_groups.json
  def create
    @payload_group = PayloadGroup.new(params[:payload_group])

    respond_to do |format|
      if @payload_group.save
        format.html { redirect_to @payload_group, notice: 'Payload group was successfully created.' }
        format.json { render json: @payload_group, status: :created, location: @payload_group }
      else
        format.html { render action: "new" }
        format.json { render json: @payload_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payload_groups/1
  # PUT /payload_groups/1.json
  def update
    @payload_group = PayloadGroup.find(params[:id])

    respond_to do |format|
      if @payload_group.update_attributes(params[:payload_group])
        format.html { redirect_to @payload_group, notice: 'Payload group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payload_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payload_groups/1
  # DELETE /payload_groups/1.json
  def destroy
    @payload_group = PayloadGroup.find(params[:id])
    @payload_group.destroy

    respond_to do |format|
      format.html { redirect_to payload_groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/gyro_parts_helper.rb
module GyroPartsHelper
end

app/helpers/gyros_helper.rb
module GyrosHelper
end

app/helpers/payload_groups_helper.rb
module PayloadGroupsHelper
end

app/helpers/payloads_helper.rb
module PayloadsHelper
  def payload_linkable(txt, obj,  payload, action = nil, css) 
    if obj.is_a?(Server)
      link_to txt, run_payload_server_path(obj.id, payload.id, :package_action => action), :class => css, :remote => true
    elsif obj.is_a?(ServerGroup)
      link_to txt, run_payload_payload_group_path(obj.id, payload.id, :package_action => action), :class => css, :remote => true
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rocket_files_helper.rb
module RocketFilesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/payload_groups/_form.html.haml
= simple_form_for @payload_group, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), payload_groups_path, :class => 'btn'

app/views/payload_groups/edit.html.haml
- model_class = @payload_group.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/payload_groups/index.html.haml
- model_class = PayloadGroup.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @payload_groups.each do |payload_group|
      %tr
        %td= link_to payload_group.id, payload_group_path(payload_group)
        %td= link_to payload_group.name, payload_group
        %td=l payload_group.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_payload_group_path(payload_group), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), payload_group_path(payload_group), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_payload_group_path, :class => 'btn btn-primary'

app/views/payload_groups/new.html.haml
- model_class = @payload_group.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/payload_groups/show.html.haml
- model_class = @payload_group.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @payload_group.name

= form_for :pg, :url => add_payload_payload_group_path(@payload_group) do |f|
  = select('pg', 'payload_id', Payload.values_of(:name, :id))
  = submit_tag "+", :class => "btn btn-primary btn-small"

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), payload_groups_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_payload_group_path(@payload_group), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), payload_group_path(@payload_group), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'

= render 'payload_group_payloads/list'