config/routes.rb
RocketProvisioner::Application.routes.draw do

  get "report_instances/show"

  get "report_instances/index"

  resources :report_results

  resources :reports do 
    resources :report_instances
    member do 
      get 'run'
    end
  end


  resources :rocket_files

  resources :folders

  resources :payload_groups do 
    member do 
      get 'run/:object_type/:object_id', :to => "payload_groups#run", :as => "run"
      post 'add_payload'
      get 'payload/:payload_id/run', :as => 'run_payload', :to => "server_groups#run"
    end
  end


  resources :payloads

  resources :server_roles

  resources :payload_histories

  resources :servers do 
    resources :payload_histories
    member do 
      get 'payload/:payload_id/run', :as => 'run_payload', :to => "servers#run"
    end
  end

  root :to => "server_groups#index"

  resources :server_groups

  require 'resque'

  mount Resque::Server.new, :at => "/resque"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name
end

app/models/installed_payload.rb
class InstalledPayload < ActiveRecord::Base
  attr_accessible :payload_id, :server_id
end

app/models/payload.rb
class Payload < ActiveRecord::Base
  attr_accessible :name, :script, :payload_type
  belongs_to :payload_group_payloads
  scope :scripts, where(:payload_type => 'script')
  scope :packages, where(:payload_type => 'package')
  def to_s 
    name
  end
end

app/models/payload_group.rb
class PayloadGroup < ActiveRecord::Base
  attr_accessible :name
  has_many :payload_group_payloads
  has_many :payloads, :through => :payload_group_payloads
  validates_presence_of :name
end

app/models/payload_history.rb
class PayloadHistory < ActiveRecord::Base
  attr_accessible :output, :payload_id, :return_code, :server_id, :finished
  belongs_to :payload 
  belongs_to :server

  default_scope order('id desc')
  scope :pending, where(:finished => false)
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :name, :payload_id
  has_many :report_instances
  belongs_to :payload
end

app/models/report_instance.rb
class ReportInstance < ActiveRecord::Base
  attr_accessible :report_id
  belongs_to :report 
  has_many :report_results
end

app/models/report_result.rb
class ReportResult < ActiveRecord::Base
  attr_accessible :report_id, :result, :server_id, :report_instance_id
  belongs_to :report 
  belongs_to :report_instance
  belongs_to :server
end

app/models/rocket_file.rb
class RocketFile < ActiveRecord::Base
  attr_accessible :content, :folder_id, :name
end

app/models/server.rb
class Server < ActiveRecord::Base
  attr_accessible :dns_name, :ip_address, :server_group_id, :server_role_id, :ssh_user
  validates_presence_of :server_group_id, :dns_name, :ip_address
  belongs_to :server_group
  belongs_to :server_role

  has_many :payload_history

  def payload_installed?(payload)
    InstalledPayload.where(:server_id => self.id, :payload_id => payload.id).count > 0 ? true : false
  end

  def to_s 
    "#{dns_name} (#{ip_address})"
  end

end

app/models/server_group.rb
class ServerGroup < ActiveRecord::Base
  attr_accessible :name
  has_many :servers

  def to_s 
    name
  end
end

app/models/server_role.rb
class ServerRole < ActiveRecord::Base
  attr_accessible :name
  has_many :servers
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def run
    @report = Report.find(params[:id])
    payload_id = @report.payload_id
    @report_instance = ReportInstance.create(report_id: @report.id)
    Server.all.each do |server| 
      ph = PayloadHistory.create(server_id: server.id, payload_id: payload_id)
      Server.increment_counter(:pending_payloads, server.id)
      Resque.enqueue(PayloadRunner, payload_id, server.id, '', ph.id, @report_instance.id)
    end
    redirect_to reports_path
  end
  
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/gyro_parts_helper.rb
module GyroPartsHelper
end

app/helpers/gyros_helper.rb
module GyrosHelper
end

app/helpers/payloads_helper.rb
module PayloadsHelper
  def payload_linkable(txt, obj,  payload, action = nil, css) 
    if obj.is_a?(Server)
      link_to txt, run_payload_server_path(obj.id, payload.id, :package_action => action), :class => css, :remote => true
    elsif obj.is_a?(ServerGroup)
      link_to txt, run_payload_payload_group_path(obj.id, payload.id, :package_action => action), :class => css, :remote => true
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/rocket_files_helper.rb
module RocketFilesHelper
end

app/helpers/server_roles_helper.rb
module ServerRolesHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/reports/_form.html.haml
= simple_form_for @report, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.input :name
  .control-group
    = f.input :payload_id, :collection => Payload.scripts
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), reports_path, :class => 'btn'

app/views/reports/edit.html.haml
- model_class = @report.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/reports/index.html.haml
- model_class = Report.new.class
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:payload_id)
      %th Last Run
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @reports.each do |report|
      %tr
        %td= link_to report.id, report_path(report)
        %td= link_to report.name, report
        %td= report.payload.name
        - report_instance = report.report_instances.last
        - if report_instance
          %td=link_to report_instance.created_at, report_report_instance_path(report, report_instance.id)
        - else 
          %td Never Run
        %td
          = link_to "Run", run_report_path(report), :class => 'btn btn-primary btn-mini'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_report_path(report), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), report_path(report), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_report_path, :class => 'btn btn-primary'

app/views/reports/new.html.haml
- model_class = @report.class
.page-header
  %h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/reports/show.html.haml
%h1= @report.name
= @report.payload.name

%table.table
  %tr 
    %th Date
    %th Results
  - @report.report_instances.each do |ri| 
    %tr 
      %td= link_to ri.created_at, report_report_instance_path(@report, ri)
      %td= ri.report_results.count